# Generated by Django 4.2.3 on 2023-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(blank=True)),
                ('reg_name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField(blank=True)),
                ('full_name', models.CharField(max_length=100)),
                ('dof', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('file_number', models.IntegerField(blank=True)),
                ('role', models.CharField(max_length=150)),
                ('marital_status', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=50)),
                ('nhci', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.IntegerField()),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('street_chairman', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_cell_leader', models.CharField(blank=True, max_length=100, null=True)),
                ('street_chair_man_contact', models.IntegerField(blank=True, null=True)),
                ('client_contact', models.IntegerField()),
            ],
        ),
    ]
