# Generated by Django 4.2.3 on 2023-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_doctors_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='experience',
            field=models.TextField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='doctors',
            name='training',
            field=models.TextField(default='college training', max_length=255),
        ),
    ]
