# Generated by Django 4.2.3 on 2023-09-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_doctors_experience_doctors_training'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Staff',
        ),
    ]
