# Generated by Django 4.2.3 on 2024-03-11 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_remove_customers_nhci_customers_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
