# Generated by Django 4.2.3 on 2024-03-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_remove_medication_cases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='full_name',
            new_name='name',
        ),
    ]
