# Generated by Django 4.2.3 on 2024-03-19 00:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_rename_full_name_customers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='lab_result',
            name='result_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lab_result',
            name='sample_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lab_result',
            name='sample_date_returned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
