# Generated by Django 4.2.3 on 2024-03-19 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_alter_customers_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
