# Generated by Django 4.2.3 on 2024-03-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_alter_customers_date_created_alter_medication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.CharField(max_length=100)),
                ('reject', models.CharField(max_length=100)),
            ],
        ),
    ]
