# Generated by Django 4.2.3 on 2024-03-21 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('id_number', models.IntegerField(null=True)),
                ('dof', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('case_description', models.TextField(null=True)),
                ('full_name_new', models.TextField(null=True)),
                ('description_new', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('visit_date', models.DateField()),
                ('visit_case', models.TextField(default='Body Checkup')),
                ('case_description_new', models.TextField(null=True)),
                ('doctor_name', models.CharField(max_length=200)),
                ('visit_time', models.TimeField(null=True)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
