# Generated by Django 4.2.3 on 2024-03-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='dof',
            field=models.TextField(null=True),
        ),
    ]
