# Generated by Django 4.2.3 on 2024-03-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_alter_admission_dof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='end_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='start_date',
            field=models.TextField(null=True),
        ),
    ]
