# Generated by Django 4.2.3 on 2024-03-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0021_alter_admission_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
