# Generated by Django 4.2.3 on 2024-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0022_alter_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='day',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
