# Generated by Django 4.2.3 on 2024-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0023_customers_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='day',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
