# Generated by Django 4.2.3 on 2024-03-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0025_custommodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModel',
        ),
    ]
