# Generated by Django 5.0.4 on 2024-05-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0027_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='card_number',
        ),
    ]
