# Generated by Django 5.0.4 on 2024-05-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0028_remove_customers_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_number', models.IntegerField()),
                ('payment_day', models.CharField(max_length=100)),
                ('payment_time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('visit_case', models.TextField(max_length=300)),
                ('cost', models.FloatField()),
                ('control_number', models.IntegerField()),
            ],
        ),
    ]
