# Generated by Django 5.0.4 on 2024-06-12 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0030_rename_name_payments_payer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('specialty', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2024, 6, 13, 1, 13, 43, 850018))),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
