# Generated by Django 5.0.4 on 2024-06-13 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0032_alter_accepted_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('specialty', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('day', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
