from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('home', views.home, name='home'),
    path('logout', views.logout, name='logout'),
    path('customer', views.customer, name='customer'),
    path('demographic', views.demographic, name='demographic'),
    path('reception', views.reception, name='reception'),
    path('register', views.register, name='register'),
    path('prescription', views.prescription, name='prescription'),
    path('Test', views.Test, name='Test'),
    path('appointment<int:pk>', views.appointment, name='appointment'),
    path('Book_appointment', views.Book_appointment, name='Book_appointment'),
    path('manage_appointment', views.manage_appointment, name='manage_appointment'),
    path('medication', views.medication, name='medication'),
    path('medicationQuery',views.medicationQuery, name='medicationQuery'),
    path('appointmentList<int:pk>', views.appointmentList, name='appointmentList'),
    path('doctor', views.doctor, name='doctor'),
    path('RegDoc', views.RegDoc, name='RegDoc'),
    path('user_data', views.user_data, name='user_data'),
    path('prescriptions', views.prescriptions, name='prescriptions'),
    path('existing_prescriptions<int:pk>', views.existing_prescriptions, name='existing_prescriptions'),
    path('searchData', views.searchData, name='searchData'),
    path('status', views.status, name='status'),
    path('edit_appointment<int:pk>', views.edit_appointment, name='edit_appointment'),
    path('delete_appointment<int:pk>', views.delete_appointment, name='delete_appointment'),
    path('admit_patient<int:pk>', views.admit_patient, name='admit_patient'),
    path('staff_specialty', views.staff_specialty, name='staff_specialty'),
    path('admission', views.admission, name='admission'),
    path('edit_staff<int:pk>', views.edit_staff, name='edit_staff'),
    path('delete_staff<int:pk>', views.delete_staff, name='delete_staff'),
    path('edit_patient<int:pk>', views.edit_patient, name='edit_patient'),
    path('delete_patient<int:pk>', views.delete_patient, name='delete_patient'),
    path('discharge', views.discharge, name='discharge'),
    path('discharge_patient<int:pk>', views.discharge_patient, name='discharge_patient'),
    path('trends', views.trends, name='trends'),
    path('patient', views.patient, name='patient'),
]
